package com.medplus.marketing_automation_backend.service;

import com.medplus.marketing_automation_backend.domain.AssetInfo;
import com.medplus.marketing_automation_backend.domain.ApprovalLog;
import com.medplus.marketing_automation_backend.domain.AutoCreatedTask;
import com.medplus.marketing_automation_backend.domain.User;
import com.medplus.marketing_automation_backend.domain.WorkTask;
import com.medplus.marketing_automation_backend.dto.WorkTaskResponse;
import com.medplus.marketing_automation_backend.enums.ApprovalAction;
import com.medplus.marketing_automation_backend.enums.TaskStatus;
import com.medplus.marketing_automation_backend.exception.BadRequestException;
import com.medplus.marketing_automation_backend.exception.ResourceNotFoundException;
import com.medplus.marketing_automation_backend.event.TaskAssignedEvent;
import com.medplus.marketing_automation_backend.event.ManagerReworkEvent;
import com.medplus.marketing_automation_backend.event.TaskCancelledEvent;
import com.medplus.marketing_automation_backend.event.ContentTaskAutoClosedEvent;
import com.medplus.marketing_automation_backend.repository.ApprovalLogRepository;
import com.medplus.marketing_automation_backend.repository.AssetInfoRepository;
import com.medplus.marketing_automation_backend.repository.AutoCreatedTaskRepository;
import com.medplus.marketing_automation_backend.repository.CollaboratorRepository;
import com.medplus.marketing_automation_backend.repository.UserRepository;
import com.medplus.marketing_automation_backend.repository.WorkTaskRepository;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
public class AutoCreatedTaskService {

    private static final String DEFAULT_CONTENT_GRANULAR_TASK_ID = "TASK-AUTO-CONTENT";

    private final AutoCreatedTaskRepository autoCreatedTaskRepo;
    private final WorkTaskRepository        workTaskRepo;
    private final UserRepository            userRepo;
    private final CollaboratorRepository    collaboratorRepo;
    private final QuestionnaireService      questionnaireService;
    private final AssetInfoRepository       assetInfoRepo;
    private final ApprovalLogRepository     approvalLogRepo;
    private final ApplicationEventPublisher eventPublisher;

    public AutoCreatedTaskService(AutoCreatedTaskRepository autoCreatedTaskRepo,
                                  WorkTaskRepository workTaskRepo,
                                  UserRepository userRepo,
                                  CollaboratorRepository collaboratorRepo,
                                  QuestionnaireService questionnaireService,
                                  AssetInfoRepository assetInfoRepo,
                                  ApprovalLogRepository approvalLogRepo,
                                  ApplicationEventPublisher eventPublisher) {
        this.autoCreatedTaskRepo = autoCreatedTaskRepo;
        this.workTaskRepo = workTaskRepo;
        this.userRepo = userRepo;
        this.collaboratorRepo = collaboratorRepo;
        this.questionnaireService = questionnaireService;
        this.assetInfoRepo = assetInfoRepo;
        this.approvalLogRepo = approvalLogRepo;
        this.eventPublisher = eventPublisher;
    }

    public boolean isAutoGeneratedTask(String taskId) {
        return autoCreatedTaskRepo.findByCreatedTaskId(taskId).isPresent();
    }

    /** Returns the user ID of the designer who requested this content task, if found. */
    public java.util.Optional<Integer> findRequesterByContentTaskId(String contentTaskId) {
        return autoCreatedTaskRepo.findByCreatedTaskId(contentTaskId)
                .map(AutoCreatedTask::getRequestedByUserId);
    }

    @Transactional
    public WorkTaskResponse requestContent(String sourceTaskId, int requesterUserId) {
        WorkTask source = workTaskRepo.findById(sourceTaskId)
                .orElseThrow(() -> new ResourceNotFoundException("Task not found: " + sourceTaskId));
        if (source.getAssignedTo() == null || source.getAssignedTo() != requesterUserId) {
            throw new BadRequestException("Only the assigned designer can request content for this task.");
        }
        User requester = userRepo.findById((long) requesterUserId)
                .orElseThrow(() -> new ResourceNotFoundException("User not found: " + requesterUserId));
        if (!requester.hasRole("Graphic Designer")) {
            throw new BadRequestException("Only Graphic Designers can request supporting content.");
        }
        if (source.getStatus() == TaskStatus.COMPLETED
                || source.getStatus() == TaskStatus.CANCELLED
                || source.getStatus() == TaskStatus.REJECTED) {
            throw new BadRequestException("Cannot request content on a closed task.");
        }
        if (autoCreatedTaskRepo.findBySourceTaskId(sourceTaskId).isPresent()) {
            if (source.getStatus() == TaskStatus.REWORK) {
                return requestContentRework(sourceTaskId, requesterUserId);
            }
            throw new BadRequestException("Content has already been requested for this task.");
        }

        User writer = userRepo.findBestAvailableContentWriter(requesterUserId)
                .orElseThrow(() -> new BadRequestException("No available Content Writer found."));
        WorkTask child = WorkTask.builder()
                .campaignId(source.getCampaignId())
                .assignedTo(writer.getUserId().intValue())
                .granularTaskId(DEFAULT_CONTENT_GRANULAR_TASK_ID)
                .status(TaskStatus.ASSIGNED)
                .build();
        String childTaskId = workTaskRepo.insert(child);
        userRepo.incrementActiveTasks(writer.getUserId());
        collaboratorRepo.addSingleCollaborator(childTaskId, requesterUserId);
        questionnaireService.savePrefilledAnswers(childTaskId, DEFAULT_CONTENT_GRANULAR_TASK_ID, null);

        autoCreatedTaskRepo.insert(AutoCreatedTask.builder()
                .sourceTaskId(sourceTaskId)
                .createdTaskId(childTaskId)
                .campaignId(source.getCampaignId())
                .sourceGranularTaskId(source.getGranularTaskId())
                .contentGranularTaskId(DEFAULT_CONTENT_GRANULAR_TASK_ID)
                .requestedByUserId(requesterUserId)
                .contentAssigneeUserId(writer.getUserId().intValue())
                .status("REQUESTED")
                .build());

        // Notify content writer that a task was assigned
        eventPublisher.publishEvent(new TaskAssignedEvent(childTaskId, writer.getUserId().intValue(), "Auto Content Writing"));

        return enrich(CampaignService.toWorkTaskResponse(
                workTaskRepo.findById(sourceTaskId).orElseThrow()));
    }

    @Transactional
    public WorkTaskResponse requestContentRework(String sourceTaskId, int requesterUserId) {
        WorkTask source = workTaskRepo.findById(sourceTaskId)
                .orElseThrow(() -> new ResourceNotFoundException("Task not found: " + sourceTaskId));
        if (source.getAssignedTo() == null || source.getAssignedTo() != requesterUserId) {
            throw new BadRequestException("Only the assigned designer can request content for this task.");
        }
        User requester = userRepo.findById((long) requesterUserId)
                .orElseThrow(() -> new ResourceNotFoundException("User not found: " + requesterUserId));
        if (!requester.hasRole("Graphic Designer")) {
            throw new BadRequestException("Only Graphic Designers can request supporting content.");
        }
        if (source.getStatus() != TaskStatus.REWORK) {
            throw new BadRequestException("Content rework can only be requested when the task is in REWORK.");
        }
        autoCreatedTaskRepo.findBySourceTaskId(sourceTaskId)
                .orElseThrow(() -> new BadRequestException("No linked content request exists for this task."));

        syncReworkToLinkedContentTask(sourceTaskId);

        return enrich(CampaignService.toWorkTaskResponse(
                workTaskRepo.findById(sourceTaskId).orElseThrow()));
    }

    public List<WorkTaskResponse> enrichAll(List<WorkTaskResponse> responses) {
        if (responses == null || responses.isEmpty()) return responses;
        List<String> taskIds = responses.stream().map(WorkTaskResponse::getTaskId).toList();
        Map<String, AutoCreatedTask> bySource = autoCreatedTaskRepo.findBySourceTaskIds(taskIds).stream()
                .collect(Collectors.toMap(AutoCreatedTask::getSourceTaskId, row -> row, (a, b) -> a));
        Map<String, AutoCreatedTask> byChild = autoCreatedTaskRepo.findByCreatedTaskIds(taskIds).stream()
                .collect(Collectors.toMap(AutoCreatedTask::getCreatedTaskId, row -> row, (a, b) -> a));
        Map<Integer, String> names = new HashMap<>();
        for (AutoCreatedTask row : bySource.values()) {
            cacheAutoCreatedUserNames(row, names);
        }
        for (AutoCreatedTask row : byChild.values()) {
            cacheAutoCreatedUserNames(row, names);
        }

        // Batch-fetch the actual work-task status for all linked content tasks so the
        // frontend knows whether the content task is already in REWORK state.
        List<String> contentTaskIds = bySource.values().stream()
                .map(AutoCreatedTask::getCreatedTaskId)
                .collect(Collectors.toList());
        Map<String, String> contentTaskStatusMap = new HashMap<>();
        if (!contentTaskIds.isEmpty()) {
            workTaskRepo.findByIds(contentTaskIds).forEach(wt ->
                    contentTaskStatusMap.put(wt.getTaskId(),
                            wt.getStatus() != null ? wt.getStatus().name() : null));
        }

        for (WorkTaskResponse response : responses) {
            AutoCreatedTask sourceLink = bySource.get(response.getTaskId());
            if (sourceLink != null) {
                response.setLinkedContentTaskId(sourceLink.getCreatedTaskId());
                response.setContentAssigneeName(names.get(sourceLink.getContentAssigneeUserId()));
                response.setContentRequestedByName(names.get(sourceLink.getRequestedByUserId()));
                response.setContentRequestStatus(sourceLink.getStatus());
                response.setContentTaskStatus(contentTaskStatusMap.get(sourceLink.getCreatedTaskId()));
            }
            AutoCreatedTask childLink = byChild.get(response.getTaskId());
            if (childLink != null) {
                response.setAutoGenerated(true);
                response.setSourceTaskId(childLink.getSourceTaskId());
                response.setContentRequestedByName(names.get(childLink.getRequestedByUserId()));
                response.setContentRequestStatus(childLink.getStatus());
            }
        }
        return responses;
    }

    public WorkTaskResponse enrich(WorkTaskResponse response) {
        if (response == null) return null;
        enrichAll(List.of(response));
        return response;
    }

    public List<AssetInfo> getContentDeliverables(String sourceTaskId, int requesterUserId) {
        WorkTask source = workTaskRepo.findById(sourceTaskId)
                .orElseThrow(() -> new ResourceNotFoundException("Task not found: " + sourceTaskId));
        if (source.getAssignedTo() == null || source.getAssignedTo() != requesterUserId) {
            throw new BadRequestException("Only the assigned designer can view requested content.");
        }
        AutoCreatedTask link = autoCreatedTaskRepo.findBySourceTaskId(sourceTaskId)
                .orElseThrow(() -> new ResourceNotFoundException("No content request exists for this task."));
        return assetInfoRepo.findByTaskId(link.getCreatedTaskId());
    }

    public void markInProgress(String createdTaskId) {
        autoCreatedTaskRepo.findByCreatedTaskId(createdTaskId).ifPresent(row -> {
            if (!"IN_PROGRESS".equals(row.getStatus())) {
                autoCreatedTaskRepo.updateStatus(row.getAutoCreatedTaskId(), "IN_PROGRESS");
            }
        });
    }

    public void markCompleted(String createdTaskId) {
        autoCreatedTaskRepo.findByCreatedTaskId(createdTaskId).ifPresent(row ->
                autoCreatedTaskRepo.updateStatus(row.getAutoCreatedTaskId(), "COMPLETED"));
    }

    /**
     * Called when the source (designer) task is submitted for QC review.
     * Closes the linked auto-generated content task if it is still open:
     *   - ASSIGNED (writer never started)  → CANCELLED
     *   - IN_PROGRESS / REWORK             → COMPLETED (writer contributed work)
     *   - Already terminal                 → no-op
     * Also decrements the content writer's active-task counter and deactivates
     * the collaboration session so no further uploads are accepted.
     */
    /**
     * When a designer source task is cancelled or rejected, auto-cancel its linked
     * content task if still open (ASSIGNED, IN_PROGRESS, or REWORK).
     */
    @Transactional
    public void cancelLinkedContentTaskOnSourceCancelledOrRejected(String sourceTaskId, String reason) {
        autoCreatedTaskRepo.findBySourceTaskId(sourceTaskId).ifPresent(link -> {
            String contentTaskId = link.getCreatedTaskId();
            WorkTask child = workTaskRepo.findById(contentTaskId).orElse(null);
            if (child == null) return;

            TaskStatus status = child.getStatus();
            if (status != TaskStatus.ASSIGNED
                    && status != TaskStatus.IN_PROGRESS
                    && status != TaskStatus.REWORK) {
                return;
            }

            workTaskRepo.markCancelled(contentTaskId);
            if (child.getAssignedTo() != null) {
                userRepo.decrementActiveTasks(child.getAssignedTo().longValue());
                eventPublisher.publishEvent(
                        new TaskCancelledEvent(contentTaskId, reason, child.getAssignedTo()));
            }
            workTaskRepo.deactivateCollaboration(contentTaskId);
            autoCreatedTaskRepo.updateStatus(link.getAutoCreatedTaskId(), "CANCELLED");
        });
    }

    @Transactional
    public void closeLinkedContentTaskOnSourceQcSubmit(String sourceTaskId) {
        autoCreatedTaskRepo.findBySourceTaskId(sourceTaskId).ifPresent(link -> {
            String contentTaskId = link.getCreatedTaskId();
            WorkTask child = workTaskRepo.findById(contentTaskId).orElse(null);
            if (child == null) return;

            TaskStatus status = child.getStatus();
            if (status == TaskStatus.COMPLETED
                    || status == TaskStatus.CANCELLED
                    || status == TaskStatus.REJECTED) {
                return; // already terminal — nothing to do
            }

            if (status == TaskStatus.ASSIGNED) {
                // Content writer never started — cancel it
                workTaskRepo.markCancelled(contentTaskId);
                // Notify writer that the task was auto-cancelled (designer submitted for QC)
                if (child.getAssignedTo() != null) {
                    eventPublisher.publishEvent(
                            new TaskCancelledEvent(contentTaskId, "System (Designer submitted for QC)", child.getAssignedTo()));
                }
            } else {
                // IN_PROGRESS or REWORK — writer did some work; mark complete (skip both QC stages)
                workTaskRepo.markRequestorApproved(contentTaskId);
                // Notify writer their task was auto-completed (designer submitted for QC)
                if (child.getAssignedTo() != null) {
                    eventPublisher.publishEvent(
                            new ContentTaskAutoClosedEvent(contentTaskId, child.getAssignedTo()));
                }
            }

            if (child.getAssignedTo() != null) {
                userRepo.decrementActiveTasks(child.getAssignedTo().longValue());
            }
            workTaskRepo.deactivateCollaboration(contentTaskId);
            autoCreatedTaskRepo.updateStatus(link.getAutoCreatedTaskId(), "COMPLETED");
        });
    }

    @Transactional
    public void syncReworkToLinkedContentTask(String sourceTaskId) {
        autoCreatedTaskRepo.findBySourceTaskId(sourceTaskId).ifPresent(link -> {
            WorkTask child = workTaskRepo.findById(link.getCreatedTaskId())
                    .orElseThrow(() -> new ResourceNotFoundException(
                            "Linked content task not found: " + link.getCreatedTaskId()));

            if (child.getStatus() == TaskStatus.CANCELLED || child.getStatus() == TaskStatus.REJECTED) {
                throw new BadRequestException("Cannot request content rework on a closed linked task.");
            }

            boolean alreadyInRework = child.getStatus() == TaskStatus.REWORK;
            if (!alreadyInRework) {
                workTaskRepo.markRework(link.getCreatedTaskId());
                if (child.getStatus() == TaskStatus.COMPLETED && child.getAssignedTo() != null) {
                    userRepo.incrementActiveTasks(child.getAssignedTo().longValue());
                }
                autoCreatedTaskRepo.updateStatus(link.getAutoCreatedTaskId(), "REQUESTED");
                // Mirror the QC rework note to the content task only when transitioning into REWORK
                mirrorLatestNeedsReworkToChild(sourceTaskId, link.getCreatedTaskId());
                // Notify content writer that rework is required
                if (child.getAssignedTo() != null) {
                    String requesterName = userRepo.findById((long) link.getRequestedByUserId())
                            .map(User::getFullName).orElse("Designer");
                    eventPublisher.publishEvent(
                            new ManagerReworkEvent(link.getCreatedTaskId(), requesterName, child.getAssignedTo()));
                }
            }
        });
    }

    public void assertRequestorCannotAccessAutoContentTask(String taskId, int userId) {
        autoCreatedTaskRepo.findByCreatedTaskId(taskId).ifPresent(link -> {
            WorkTask child = workTaskRepo.findById(taskId)
                    .orElseThrow(() -> new ResourceNotFoundException("Task not found: " + taskId));
            if (child.getRequestorId() != null && child.getRequestorId() == userId) {
                throw new BadRequestException("Campaign requestor cannot access auto-generated child tasks.");
            }
        });
    }

    private void mirrorLatestNeedsReworkToChild(String sourceTaskId, String childTaskId) {
        approvalLogRepo.findLatestByTaskIdAndAction(sourceTaskId, ApprovalAction.NEEDS_REWORK)
                .ifPresent(log -> approvalLogRepo.insert(ApprovalLog.builder()
                        .taskId(childTaskId)
                        .reviewerId(log.getReviewerId())
                        .actionTaken(ApprovalAction.NEEDS_REWORK)
                        .comments(log.getComments())
                        .build()));
    }

    private void cacheAutoCreatedUserNames(AutoCreatedTask row, Map<Integer, String> names) {
        if (row.getContentAssigneeUserId() != null) {
            names.putIfAbsent(row.getContentAssigneeUserId(),
                    resolveUserName(row.getContentAssigneeUserId()));
        }
        if (row.getRequestedByUserId() != null) {
            names.putIfAbsent(row.getRequestedByUserId(),
                    resolveUserName(row.getRequestedByUserId()));
        }
    }

    private String resolveUserName(int userId) {
        return userRepo.findById((long) userId).map(User::getFullName).orElse(null);
    }
}
