package com.medplus.marketing_automation_backend.enums;

import java.util.Arrays;
import java.util.Optional;

/**
 * Enum-driven catalog of all master lookup tables.
 * Every table has the same shape: (idColumn, nameColumn, status).
 * IDs are stored as sequential numeric strings ("1", "2", "3", …)
 * generated by the application via MAX(CAST(id AS UNSIGNED)) + 1.
 */
public enum MasterTableType {

    DEPARTMENTS        ("departments",         "/departments",          "department_id",         "department_name"),
    DESIGNATIONS       ("designations",        "/designations",         "designation_id",        "designation_name"),
    ROLES              ("roles",               "/roles",                "role_id",               "role_name"),
    REQUIREMENT_TYPES  ("requirement_types",   "/requirement-types",    "requirement_type_id",   "requirement_name"),
    TASK_TYPES         ("task_types",          "/task-types",           "task_type_id",          "task_name"),
    REGIONS            ("regions",             "/regions",              "region_id",             "region_name"),
    AUDIENCES          ("audiences",           "/audiences",            "audience_id",           "audience_name"),
    OFFER_TYPES        ("offer_types",         "/offer-types",          "offer_type_id",         "offer_type_name"),
    VENDOR_TYPES       ("vendor_types",        "/vendor-types",         "vendor_type_id",        "vendor_type_name"),
    BUSINESS_OBJECTIVES("business_objectives", "/business-objectives",  "business_objective_id", "business_objective_name"),
    LANGUAGES          ("languages",           "/languages",            "language_id",           "language_name"),
    TONES              ("tones",               "/tones",                "tone_id",               "tone_name"),
    SUPPORTING_PROOFS  ("supporting_proofs",   "/supporting-proofs",    "supporting_proof_id",   "supporting_proof_name"),
    BUDGET_TIERS       ("budget_tiers",        "/budget-tiers",         "budget_tier_id",        "budget_tier_name"),
    KPI_TYPES          ("kpi_types",           "/kpi-types",            "kpi_type_id",           "kpi_type_name"),
    EXPECTED_OUTPUTS   ("expected_outputs",    "/expected-outputs",     "expected_output_id",    "expected_output_name"),
    CAMPAIGN_TYPES     ("campaign_types",      "/campaign-types",       "campaign_type_id",      "campaign_type_name"),
    BUSINESS_VERTICALS ("business_verticals",  "/business-verticals",   "business_vertical_id",  "business_vertical_name"),
    BUSINESS_TYPES     ("business_types",      "/business-types",       "business_type_id",      "business_type_name"),
    STORE_FORMAT_TYPES ("store_format_types",  "/store-format-types",   "store_format_type_id",  "store_format_type_name");

    private final String tableName;
    private final String pathSlug;
    private final String idColumn;
    private final String nameColumn;

    MasterTableType(String tableName, String pathSlug, String idColumn, String nameColumn) {
        this.tableName  = tableName;
        this.pathSlug   = pathSlug;
        this.idColumn   = idColumn;
        this.nameColumn = nameColumn;
    }

    public String tableName()  { return tableName; }
    public String pathSlug()   { return pathSlug; }
    public String idColumn()   { return idColumn; }
    public String nameColumn() { return nameColumn; }

    /** Resolve a path slug (e.g. "departments" or "business-objectives"). */
    public static Optional<MasterTableType> fromSlug(String slug) {
        if (slug == null) return Optional.empty();
        String norm = "/" + slug.toLowerCase().replace('_', '-');
        return Arrays.stream(values()).filter(v -> v.pathSlug.equals(norm)).findFirst();
    }
}
